### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by michelaburns** [codeu-spring2019/whats-that-doggo#11]
Hello guys! For this final week, we need to integrate the frontend. Below I'll be providing resources on how to and notes. Feel free to leave comments, contributions, and questions!

**Things to think about / research (provided by Matt):**

- [x] POST’ing the image captured from the user to the backend (Function) URL

- [x] handling the JSON body returned

- [x] updating the .innerText element with the JSON object’s elements (label, score)

- [x] handling errors - maybe have a HTML element like a <span> tag that you update with the error text. Change the style attribute from “display: none” (default) when you populate the .innerText so it shows up, but hide it otherwise?

- Fetch API: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

**Comment by michelaburns** [comment]
### Fetch API

- Provides a Javascript interface for accessing and manipulating parts of the HTTP pipeline, such as REQUESTS AND RESPONSES

- **Basic fetch request + explanation**
![Screen Shot 2019-04-18 at 1 00 15 AM](https://user-images.githubusercontent.com/13473746/56345769-65e3b300-6175-11e9-82b3-e7e0f8cd407e.png)

     - Within this basic example, we are fetching a JSON file across the network and printing it to the console. The simplest use of fetch() takes one argument — the path to the resource you want to fetch and returns a promise containing the response (a Response object).

     - To extract the JSON body content from this HTTP response, we use the json() method (defined on the Body mixin, which is implemented by both the Request and Response objects.)

- **Uploading JSON data**
![Screen Shot 2019-04-18 at 1 07 48 AM](https://user-images.githubusercontent.com/13473746/56346201-78aab780-6176-11e9-8fe9-30b7fc77397b.png)

     - I think this is pretty similar to what we want to do, as we will be passing our predict function an image


- **Fetch code that uses images**
![Screen Shot 2019-04-18 at 1 21 59 AM](https://user-images.githubusercontent.com/13473746/56347105-721d3f80-6178-11e9-94a1-c7c7e67eab3a.png)

### Other Resources

- https://medium.com/front-end-weekly/fetching-images-with-the-fetch-api-fb8761ed27b2

**Comment by elithrar** [comment]
The last part is definitely similar, but you’ll pass the whole image (an
array) as the body rather than call JSON.stringify(data).

The image should already be an array within the displayImage implementation
Grace & Jose pushed a couple of weeks ago.

**Comment by michelaburns** [comment]
Okay! I've drafted a js file and I'll send out a pull request in a few minutes!

`

**Comment by michelaburns** [comment]
### Handling the JSON Body Returned 

- **Example**

     - https://developer.mozilla.org/en-US/docs/Web/API/Body/json

     -![Screen Shot 2019-04-18 at 2 01 53 AM](https://user-images.githubusercontent.com/13473746/56349736-04741200-617e-11e9-96cc-ea0f7dbd4ef0.png)

     - ![Screen Shot 2019-04-18 at 2 02 53 AM](https://user-images.githubusercontent.com/13473746/56349773-1ce42c80-617e-11e9-9f76-bdcc622e2336.png)

**Comment by michelaburns** [comment]
### Updating the .innerText element with the JSON object’s elements (label, score)

- https://github.com/mdn/fetch-examples/blob/master/fetch-json/products.json

     - I used this example and combined it with the example I found on the fetch API

**Comment by michelaburns** [comment]
I've completed all of these tasks! :) Now we just have to test it, get rid of any errors, and then integrate it with the rest of the front end. See https://github.com/codeu-spring2019/whats-that-doggo/pull/12 for the function

**Comment by elithrar** [comment]
Done as of #20.
