### ISSUE TITLE
How is everyone doing?

### ISSUE THREAD

**Issue by michelaburns** [codeu-spring2019/whats-that-doggo#13]
Hi guys! Just wanted to check in with everyone and see how they're doing with their parts of the program. 

As I'm sure you guys are aware, the showcase is due tomorrow (Friday). These are the required materials

- [ ] A live app engine URL (appspot link) - Make sure your web app works on your live site. Start testing this now!

- [ ] A GitHub repo link 

- [ ] Your team’s project doc which should highlight your personal contribution 

I totally understand that we all have really busy schedules with work and school, but I'm a little worried about the live app engine URL. I'm currently working on finishing up the backend function that will allow for frontend-backend integration. I know we still need to connect both sides though. 

Additionally, just a reminder, as the last checkpoint says, make sure to highlight your personal contributions

How do you guys feel about the showcase coming up? Also, does anyone have any updates?

**Comment by elithrar** [comment]
I’m confident with the first one - we don’t have to use App Engine - any
publicly accessible URL is fine.

We’ll upload our website/ directory contents to a new bucket - and
optionally put a domain name in front of it this week.

Ref:
https://cloud.google.com/storage/docs/hosting-static-website

Function is almost complete + I will test the integration today (Friday).

**Comment by michelaburns** [comment]
Oh I see, fantastic! Thank goodness for buckets! I'm heading to bed soon, but I'll look at the reference link when I wake up. Also, I've updated the fetch function. Please let me know which changes you would like me to make :)

In regards to adding a domain name to our bucket, it would be cool if we could use something like "whats-that-doggo" as our domain name. Looking at the documentation for domain names for buckets (https://cloud.google.com/storage/docs/domain-name-verification), it looks like we'd have to verify that we have rights to the domain by proving one of the following
     - That we're verified owners of the domain or parent domain 
     - That we're verified site owners of the domain or parent domain

In regards to obtaining a domain, we would have to purchase the domain (can't _really_ purchase it, more so rent it lol). It would be great if Google/CodeU is willing to fund this, but if that's not the case, I would be open to contributing to the cost if other members of the group are interested. 

Available Domain Names:

- whats-that-doggo.com

     - https://www.godaddy.com/domainsearch/find?domainToCheck=whats-that-doggo.com
     - $1 for the first year, $19.99 for additional years

- whatsthatdoggo.com
     - https://www.godaddy.com/domainsearch/find?domainToCheck=whats-that-doggo.com
     - $1 for the first year, $19.99 for additional years

**Comment by elithrar** [comment]
I’ll buy the domain & we can verify + set it up this week! (after initial
submission)

Will buy it from Google Domains.

**Comment by elithrar** [comment]
URL with a placeholder `index.html` in the bucket: http://www.whatsthatdoggo.com/

* It fronts the `www.whatsthatdoggo.com` Google Cloud Storage (GCS) bucket
* Cloud DNS & configuration is all set up as per https://cloud.google.com/storage/docs/hosting-static-website#top_of_page
* Next step, once ready: copy the _contents_ of the `website/` directory into the bucket.

(I know I said next week, but I was waiting for the Cloud Function to deploy...)
