### ISSUE TITLE
Uploading to Showcase (Complete by Friday Night)

### ISSUE THREAD

**Issue by michelaburns** [codeu-spring2019/whats-that-doggo#14]
Due on Friday, 4-19-19 by 10 pm on http://codeu-showcase-sp19.appspot.com/

- [x] A live app engine URL (appspot link) - Make sure your web app works on your live site. Start testing this now!

     - **We need to finish this!**

- [x] A GitHub repo link

     - We have this ready

- [x] Your team’s project doc which should highlight your personal contribution

     - Basically done, but they did request that we highlight our specific roles. I did this for backend, but Jose and Grace should do so for their parts in the frontend

**Comment by michelaburns** [comment]
Hey guys! I'm going to submit our information to the showcase. We can always edit it later. This issue: https://github.com/codeu-spring2019/whats-that-doggo/issues/13 explains the public URL. Here's what I submitted:

**Title:** 
What's That Doggo

**Public URL:** 
http://www.whatsthatdoggo.com

**Github URL:** 
https://github.com/codeu-spring2019/whats-that-doggo.git

**Design Doc URL:** https://docs.google.com/document/d/1v8SzN4c6e9wDrN2SpHMsCbXikeQ49fzOr19UiBzFacY/edit?usp=sharing

**Description:**
For our open project we built a mobile web application that tells the user what breed of dog they’ve taken a photo of, in real time - by taking a photo or uploading one they’ve taken before!

This is great for people to learn dog breeds, and can be extended in the future to tell different kinds of animals, or re-purposed for an entire range of classification tasks just by training a new backend model.

**Comment by elithrar** [comment]
👏🏼👏🏼👏🏼
