### ISSUE TITLE
Final Steps

### ISSUE THREAD

**Issue by michelaburns** [codeu-spring2019/whats-that-doggo#18]
Hey guys! As Jess' recent email said, there are a few more steps left of CodeU. Below I have listed the items that each member of the group has to complete. Please see her email for other things you must accomplish individually. 

- [x] Every team member has to comment on _at least_ 2 projects on http://codeu-showcase-sp19.appspot.com . 

- [x] Within the project doc, each member of the team should include a post-mortem/reflection. I've already set up a section for this part (titled CodeU Reflections), so please just fill out the portion beside your name :)

- [x]  Project Submission & Post Program Survey

Please make sure to comment on this post once you've done these parts!

**Comment by elithrar** [comment]
Make sure to remind the other teams to check out:

- www.whatsthatdoggo.com (again) - now that we have a working app!
- Read through our README for the project description

Individually: send me an email if any questions as you write things up!

**Comment by gcheng21** [comment]
finished all 3 tasks!

**Comment by elithrar** [comment]
Example!

![C3ED1E39-213C-46F4-B4DA-AAA547247A16](https://user-images.githubusercontent.com/18544/56787284-f19fb400-67f3-11e9-9af4-b3949d36ab14.png)

**Comment by michelaburns** [comment]
SO HAPPY IT'S UP AND WORKING!! There is a small glitch with the upload button, but I can probably fix it pretty quickly this weekend :) After you click the upload button, it assumes that you want to upload more. But if you click cancel you're able to see your dog's prediction.

I tested it out on my old puppo and it worked!!! 
![IMG_5423](https://user-images.githubusercontent.com/13473746/56833620-d2b91600-6823-11e9-885a-5e61c9ef2476.jpeg)

Thank you to everyone for being a part of this wonderful project :) Seeing it up and running warms my heart.

**Comment by elithrar** [comment]
Awesome. I was thinking of a few key UX improvements:

• use setTimeout to disable the upload button for few seconds while a
prediction is running
• add a spinner that you show just prior to the fetch call and hide at the
top of .then() or .catch() /
https://tobiasahlin.com/spinkit/
- rework the html & css to better align & scale on mobile devices.

Matt
