### ISSUE TITLE
Uploading to Google Cloud Storage

### ISSUE THREAD

**Issue by michelaburns** [codeu-spring2019/whats-that-doggo#19]
Hello Matt! Now that we've (hopefully) made all of the necessary changes to our frontend and backend, as you stated in the last pull request, the next step is uploading our project to the Google Cloud Storage (GCS) www.whatsthatdoggo.com bucket.

Originally, I believe we just uploaded our frontend to the bucket. As a result, the bucket contained basically everything in the website file :

- css/ file

- index.html

- js/ file

So, now that we have the functions from the backend and integration , would the bucket contain:
- The **current** website file (which contains the css file, the js file, and index.html)

- The following items from the **current** function file 
     - fetchFile.js
     - index.js
     - package.json
     - yarn.lock

**Comment by elithrar** [comment]
Done in #20
