### ISSUE TITLE
Dataset: Prep Dataset CSV

### ISSUE THREAD

**Issue by elithrar** [codeu-spring2019/whats-that-doggo#2]
@michelaburns @jimenezjose 

- [x] Download Stanford Dogs dataset
- [x] Generate CSV of {path, label} for each of the images
- [x] Upload images to Google Cloud Storage

**Comment by michelaburns** [comment]
Hello! I have finished all of these tasks. I'm now ensuring that the CSV file has the correct paths

**Comment by michelaburns** [comment]
Additionally, I made sure the CSV file paths point to that bucket. This resulted in the folder "csv" that contains all_data.csv. This csv file paths point to the whats-that-doggo bucket. I provided instructions on how I achieved this in the "Google Cloud Tips and Tricks" Google doc.
